on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: coreg1990.azurecr.io
        username: ${{ secrets.acr_coreg1990_username }}
        password: ${{ secrets.acr_coreg1990_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t coreg1990.azurecr.io/akscluster01:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push coreg1990.azurecr.io/akscluster01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akscluster01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akscluster01bf6d | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akscluster01bf6d`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akscluster01bf6d
        container-registry-url: coreg1990.azurecr.io
        container-registry-username: ${{ secrets.acr_coreg1990_username }}
        container-registry-password: ${{ secrets.acr_coreg1990_password }}
        secret-name: akscluster01dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: akscluster01bf6d
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          coreg1990.azurecr.io/akscluster01:${{ github.sha }}
        imagepullsecrets: |
          akscluster01dockerauth
